package response;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**Creation Response returned by the rest service at immediate creation,
 * prepared creation or contribution*/
@XmlRootElement
public class CreationResponse extends Response implements Serializable{

	/**Flag indication if server operation went well or not*/
	private boolean operationStatus;
	
	/**Session public Name set by session creator*/
	private String name;
	/**Session upload rate set by session creator/contributor*/
	private int rate;
	/**Session public token generated by the server*/
	private String publicID;
	/**Session private token generated by the server*/
	private String privateID;
	/**Session starting time*/
	private Timestamp startTime;
	/**Session end time*/
	private Timestamp endTime;
	/**Session last modification time*/
	private Timestamp lastModifTime;

	public CreationResponse(boolean flag,String sessionName,int sessionRate, String publicToken,String privateToken,
			Timestamp start, Timestamp end, Timestamp lastModif) {
		super();
		this.operationStatus=flag;
		this.name=sessionName;
		this.rate=sessionRate;
		this.publicID=publicToken;
		this.privateID=privateToken;
		this.endTime=end;
		this.startTime=start;
		this.lastModifTime=lastModif;
	}
	
	
	public CreationResponse() {
		super();
		this.operationStatus=false;
		this.name=null;
		this.rate=0;
		this.publicID=null;
		this.privateID=null;
		this.endTime=null;
		this.startTime=null;
		this.lastModifTime=null;
	}

	@XmlElement
	public boolean getOperationStatus() {
		return operationStatus;
	}
	
	@XmlElement
	public String getName() {
		return this.name;
	}
	
	@XmlElement
	public int getRate() {
		return this.rate;
	}

	@XmlElement
	public String getPublicID() {
		return publicID;
	}

	@XmlElement
	public String getPrivateID() {
		return privateID;
	}

	@XmlElement
	public Timestamp getStartTime() {
		return startTime;
	}

	@XmlElement
	public Timestamp getEndTime() {
		return endTime;
	}

	@XmlElement
	public Timestamp getLastModifTime() {
		return lastModifTime;
	}

}
